name: Daily Graphic Design Post

on:
  # Schedule to run every day at 17:00 UTC, which is 1:00 AM Philippine Time (PHT).
  schedule:
    - cron: '0 17 * * *'
    
  # Allows you to run this workflow manually from the Actions tab for testing.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the AI Posting Agent
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
      run: python main.py
